POST http://localhost:3000/v1/user/sign-up/
content-type: application/json

{
    "username": "admin",
    "password": "admin",
    "confirmPassword": "admin",
    "isAdmin": "false",
    "adminCode": "123456"
}

###

POST http://localhost:3000/v1/posts
content-type: application/json

{
    "title": "test-title",
    "contents": "test-title",
    "user": "test-user",
    "isPublished": "true"
}

###

GET http://localhost:3000/v1/posts/id123
content-type: application/json

###

DELETE http://localhost:3000/v1/posts/id123/comments/
content-type: application/json

###